### ISSUE TITLE
it run ok in development enviroment, but it is wrong in production

### ISSUE THREAD

**Issue by dandandexia** [graphql/express-graphql#557]
```
[ERROR] err - Error: Expected { __validationErrors: undefined, __allowedLegacyNames: [], _queryType: enumListQuery, _mutationType: undefined, _subscriptionType: undefined, _directives: [@include, @skip, @deprecated], astNode: undefined, extensionASTNodes: undefined, _typeMap: { enumListQuery: enumListQuery, EnumInfo: EnumInfo, Int: Int, String: String, EnumTieleInfo: EnumTieleInfo, __Schema: __Schema, __Type: __Type, __TypeKind: __TypeKind, Boolean: Boolean, __Field: __Field, __InputValue: __InputValue, __EnumValue: __EnumValue, __Directive: __Directive, __DirectiveLocation: __DirectiveLocation }, _possibleTypeMap: {}, _implementations: {} } to be a GraphQL schema.
    at invariant (/node_modules/graphql/jsutils/invariant.js:13:11)
    at assertSchema (/node_modules/graphql/type/schema.js:38:46)
    at validateSchema (/node_modules/graphql/type/validate.js:44:28)
    at /node_modules/express-graphql/dist/index.js:135:64
```

**Comment by IvanGoncharov** [comment]
It looks like you are using multiple versions of `graphql-js` please run `npm ls graphql` and try to remove duplicates of `graphql`.
You can start by removing `node_modules` and running `npm install`.
